### ISSUE TITLE
0.7.5 Release Cherry-Pick PR Tracker

### ISSUE THREAD

**Issue by frostyfrog** [hyperledger/aries-cloudagent-python#1983]
This issue is to keep track of the PRs that need to be cherry picked into 0.7.5, as well as the PRs critical towards release. While there is a milestone, it can get tricky to keep track of things as more PRs get cherry picked.

Cherry picks for Milestone 0.7.5 https://github.com/hyperledger/aries-cloudagent-python/milestone/6
- [X] https://github.com/hyperledger/aries-cloudagent-python/pull/1881 (Already Merged into https://github.com/hyperledger/aries-cloudagent-python/tree/hotfix/0.7.5)
- [x] https://github.com/hyperledger/aries-cloudagent-python/pull/1940
- [X] https://github.com/hyperledger/aries-cloudagent-python/pull/1960
- [x] https://github.com/hyperledger/aries-cloudagent-python/pull/1962
- [x] https://github.com/hyperledger/aries-cloudagent-python/pull/1938
- [x] https://github.com/hyperledger/aries-cloudagent-python/pull/1926
- [x] https://github.com/hyperledger/aries-cloudagent-python/pull/1973

PRs targeted towards the release branch:
- https://github.com/hyperledger/aries-cloudagent-python/pull/1967
- https://github.com/hyperledger/aries-cloudagent-python/pull/1969
- https://github.com/hyperledger/aries-cloudagent-python/pull/1984
- https://github.com/hyperledger/aries-cloudagent-python/pull/1985

If anything, I created this to help me keep track of things better and it has the added benefit of providing some form of transparency.

**Comment by frostyfrog** [comment]
0.7.5 has been released
